manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.1.0
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: v0.1.0
    - name: zmk-auto-layer
      remote: urob
      revision: v0.1.0
      path: modules/auto-layer
  self:
    path: config
